id: QmTLqapULGiA5ZFWk2ckEjKq2B6kGVuFUF1frSAeeGjuGt
description: Function call to get messages for the database.
tags: []
source: .
trigger:
    type: https
    method: GET
    paths:
        - /messages
domains:
    - Chat_Domain
execution:
    timeout: 10s
    memory: 10GB
    call: getMessages
