id: QmTLqapULGiA5ZFWk2ckEjKq2B6kGVuFUF1frSAeeGjuGt
description: Function call to get messages for the database.
tags: []
trigger:
    type: https
    method: GET
    paths:
        - /messages
domains:
    - Chat_Domain
    - Test_Domain
includes:
    - /functions/Get_Messages.go
execution:
    timeout: 10s
    memory: 10GB
    call: getMessages
