id: QmYiQuR2K377j4ZUjxesY6a6oVvnLhzMMJsQSqmxrGZkyG
description: Function to save chat messages
tags: []
trigger:
    type: https
    method: POST
    paths:
        - /saveMessage
domains:
    - Chat_Domain
    - Test_Domain
includes:
    - /functions/Save_Messages.go
execution:
    timeout: 10s
    memory: 10GB
    call: saveMessage
