id: QmYiQuR2K377j4ZUjxesY6a6oVvnLhzMMJsQSqmxrGZkyG
description: Function to save chat messages.
tags: []
source: .
trigger:
    type: https
    method: POST
    paths:
        - /message
domains:
    - Chat_Domain
execution:
    timeout: 10s
    memory: 10GB
    call: saveMessage
